title: Jim Kennedy's Personal Site
author: Jim Kennedy
email: jim@isor.co.uk
description: CV and links
url: "https://isor.co.uk"

# Build settings
remote_theme: huangyz0918/moving
plugins:
  - jekyll-feed

moving:
  about_you: Software developer
  avatar_url: avatar.jpg
  date_format: "%b %d"
  back_to: "Index"

destination: docs/
